// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLite.MainApp.Data;

#nullable disable

namespace SQLite.MainApp.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20231120185657_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("SQLite.MainApp.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://robohash.org/autautea.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "nmorgue0@disqus.com",
                            FirstName = "Nonie",
                            LastName = "Morgue"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://robohash.org/saepeadipiscifugit.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "klowe1@nymag.com",
                            FirstName = "Krishna",
                            LastName = "Lowe"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://robohash.org/atquerepudiandaecorporis.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "owilliamson2@washingtonpost.com",
                            FirstName = "Orville",
                            LastName = "Williamson"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "https://robohash.org/liberotemporibusalias.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "ditzkovici3@phpbb.com",
                            FirstName = "Dwayne",
                            LastName = "Itzkovici"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "https://robohash.org/enimsapienteillum.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "sjerisch4@craigslist.org",
                            FirstName = "Shelbi",
                            LastName = "Jerisch"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "https://robohash.org/omnisillumnostrum.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "jwitcherley5@1und1.de",
                            FirstName = "Jerrilee",
                            LastName = "Witcherley"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "https://robohash.org/adipiscisequidolor.png?size=100x100&set=set1",
                            Department = "Marketing",
                            Email = "ckobpac6@goo.ne.jp",
                            FirstName = "Caritta",
                            LastName = "Kobpac"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "https://robohash.org/aliquamquassunt.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "qmccague7@facebook.com",
                            FirstName = "Quincey",
                            LastName = "McCague"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "https://robohash.org/eaquiserror.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "acundey8@yahoo.com",
                            FirstName = "Aharon",
                            LastName = "Cundey"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "https://robohash.org/dolorconsecteturdeleniti.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "nanthill9@posterous.com",
                            FirstName = "Neila",
                            LastName = "Anthill"
                        },
                        new
                        {
                            Id = 11,
                            Avatar = "https://robohash.org/veroculpadolore.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "cbroadera@theglobeandmail.com",
                            FirstName = "Cinnamon",
                            LastName = "Broader"
                        },
                        new
                        {
                            Id = 12,
                            Avatar = "https://robohash.org/autveritatisquibusdam.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "gtampinb@example.com",
                            FirstName = "Godfrey",
                            LastName = "Tampin"
                        },
                        new
                        {
                            Id = 13,
                            Avatar = "https://robohash.org/utvoluptasdolorum.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "oandrellic@t-online.de",
                            FirstName = "Olimpia",
                            LastName = "Andrelli"
                        },
                        new
                        {
                            Id = 14,
                            Avatar = "https://robohash.org/odioinqui.png?size=100x100&set=set1",
                            Department = "Human Resources",
                            Email = "gebblesd@fema.gov",
                            FirstName = "Grissel",
                            LastName = "Ebbles"
                        },
                        new
                        {
                            Id = 15,
                            Avatar = "https://robohash.org/saepedelenitivoluptas.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "bsutherleye@bing.com",
                            FirstName = "Beckie",
                            LastName = "Sutherley"
                        },
                        new
                        {
                            Id = 16,
                            Avatar = "https://robohash.org/aspernaturautdicta.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "dschohierf@dion.ne.jp",
                            FirstName = "Drusie",
                            LastName = "Schohier"
                        },
                        new
                        {
                            Id = 17,
                            Avatar = "https://robohash.org/dolornobisratione.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "aheisterg@soup.io",
                            FirstName = "Aida",
                            LastName = "Heister"
                        },
                        new
                        {
                            Id = 18,
                            Avatar = "https://robohash.org/estnihilsuscipit.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "vleakeh@umn.edu",
                            FirstName = "Valentia",
                            LastName = "Leake"
                        },
                        new
                        {
                            Id = 19,
                            Avatar = "https://robohash.org/abperspiciatismagnam.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "ogellatelyi@spotify.com",
                            FirstName = "Octavius",
                            LastName = "Gellately"
                        },
                        new
                        {
                            Id = 20,
                            Avatar = "https://robohash.org/blanditiisvoluptasrerum.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "emandyj@webs.com",
                            FirstName = "Erwin",
                            LastName = "Mandy"
                        },
                        new
                        {
                            Id = 21,
                            Avatar = "https://robohash.org/auteavel.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "adevenportk@google.fr",
                            FirstName = "Armand",
                            LastName = "Devenport"
                        },
                        new
                        {
                            Id = 22,
                            Avatar = "https://robohash.org/consequuntureveniethic.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "btorell@mit.edu",
                            FirstName = "Bartel",
                            LastName = "Torel"
                        },
                        new
                        {
                            Id = 23,
                            Avatar = "https://robohash.org/fugitmagnamhic.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "aludgatem@ning.com",
                            FirstName = "Auberta",
                            LastName = "Ludgate"
                        },
                        new
                        {
                            Id = 24,
                            Avatar = "https://robohash.org/voluptatumetet.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "csendalln@bizjournals.com",
                            FirstName = "Claudian",
                            LastName = "Sendall"
                        },
                        new
                        {
                            Id = 25,
                            Avatar = "https://robohash.org/cupiditateestsoluta.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "sdarrello@auda.org.au",
                            FirstName = "Saw",
                            LastName = "Darrell"
                        },
                        new
                        {
                            Id = 26,
                            Avatar = "https://robohash.org/quosconsequaturqui.png?size=100x100&set=set1",
                            Department = "Research and Development",
                            Email = "anarracottp@dedecms.com",
                            FirstName = "Arv",
                            LastName = "Narracott"
                        },
                        new
                        {
                            Id = 27,
                            Avatar = "https://robohash.org/temporibusperspiciatiscommodi.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "scloustonq@ow.ly",
                            FirstName = "Silvia",
                            LastName = "Clouston"
                        },
                        new
                        {
                            Id = 28,
                            Avatar = "https://robohash.org/eoseosdoloremque.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "fartistr@fda.gov",
                            FirstName = "Fabio",
                            LastName = "Artist"
                        },
                        new
                        {
                            Id = 29,
                            Avatar = "https://robohash.org/nihiloptiout.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "elents@wikimedia.org",
                            FirstName = "Eldredge",
                            LastName = "Lent"
                        },
                        new
                        {
                            Id = 30,
                            Avatar = "https://robohash.org/solutaarchitectovoluptate.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "agoodlettt@yellowbook.com",
                            FirstName = "Arlin",
                            LastName = "Goodlett"
                        },
                        new
                        {
                            Id = 31,
                            Avatar = "https://robohash.org/teneturquidemexercitationem.png?size=100x100&set=set1",
                            Department = "Legal",
                            Email = "fkeyseu@mac.com",
                            FirstName = "Fenelia",
                            LastName = "Keyse"
                        },
                        new
                        {
                            Id = 32,
                            Avatar = "https://robohash.org/eligenditotamdelectus.png?size=100x100&set=set1",
                            Department = "Training",
                            Email = "mshawlv@is.gd",
                            FirstName = "Merilyn",
                            LastName = "Shawl"
                        },
                        new
                        {
                            Id = 33,
                            Avatar = "https://robohash.org/dolorevoluptatibusaut.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "mwadelinw@bravesites.com",
                            FirstName = "Maryellen",
                            LastName = "Wadelin"
                        },
                        new
                        {
                            Id = 34,
                            Avatar = "https://robohash.org/delenitiomnisperferendis.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "bvanyukovx@vinaora.com",
                            FirstName = "Blondie",
                            LastName = "Vanyukov"
                        },
                        new
                        {
                            Id = 35,
                            Avatar = "https://robohash.org/nostrumharumeveniet.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "lliccardoy@unicef.org",
                            FirstName = "Leon",
                            LastName = "Liccardo"
                        },
                        new
                        {
                            Id = 36,
                            Avatar = "https://robohash.org/corporisquibusdamnisi.png?size=100x100&set=set1",
                            Department = "Engineering",
                            Email = "tburneyz@mac.com",
                            FirstName = "Theodosia",
                            LastName = "Burney"
                        },
                        new
                        {
                            Id = 37,
                            Avatar = "https://robohash.org/laudantiumillorepellendus.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "tbenedyktowicz10@indiatimes.com",
                            FirstName = "Tiffany",
                            LastName = "Benedyktowicz"
                        },
                        new
                        {
                            Id = 38,
                            Avatar = "https://robohash.org/similiquerepellatitaque.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "swathey11@fc2.com",
                            FirstName = "Salomon",
                            LastName = "Wathey"
                        },
                        new
                        {
                            Id = 39,
                            Avatar = "https://robohash.org/utmaximeet.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "fmeineking12@cbsnews.com",
                            FirstName = "Fidelio",
                            LastName = "Meineking"
                        },
                        new
                        {
                            Id = 40,
                            Avatar = "https://robohash.org/doloresomnisaut.png?size=100x100&set=set1",
                            Department = "Support",
                            Email = "fdemicoli13@earthlink.net",
                            FirstName = "Ford",
                            LastName = "De Micoli"
                        },
                        new
                        {
                            Id = 41,
                            Avatar = "https://robohash.org/nostrumdoloremqueillum.png?size=100x100&set=set1",
                            Department = "Accounting",
                            Email = "bstebbings14@bbc.co.uk",
                            FirstName = "Bridie",
                            LastName = "Stebbings"
                        },
                        new
                        {
                            Id = 42,
                            Avatar = "https://robohash.org/porroenimdolorem.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "tkarpets15@cmu.edu",
                            FirstName = "Theressa",
                            LastName = "Karpets"
                        },
                        new
                        {
                            Id = 43,
                            Avatar = "https://robohash.org/earumquiaest.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "tleivesley16@prlog.org",
                            FirstName = "Twyla",
                            LastName = "Leivesley"
                        },
                        new
                        {
                            Id = 44,
                            Avatar = "https://robohash.org/voluptatevoluptatemexcepturi.png?size=100x100&set=set1",
                            Department = "Product Management",
                            Email = "acroney17@purevolume.com",
                            FirstName = "Alane",
                            LastName = "Croney"
                        },
                        new
                        {
                            Id = 45,
                            Avatar = "https://robohash.org/possimusvoluptatesquas.png?size=100x100&set=set1",
                            Department = "Sales",
                            Email = "aurrey18@seesaa.net",
                            FirstName = "Althea",
                            LastName = "Urrey"
                        },
                        new
                        {
                            Id = 46,
                            Avatar = "https://robohash.org/magnamaliasveritatis.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "dphifer19@yale.edu",
                            FirstName = "Desiri",
                            LastName = "Phifer"
                        },
                        new
                        {
                            Id = 47,
                            Avatar = "https://robohash.org/idquaesint.png?size=100x100&set=set1",
                            Department = "Services",
                            Email = "cmeecher1a@walmart.com",
                            FirstName = "Cicily",
                            LastName = "Meecher"
                        },
                        new
                        {
                            Id = 48,
                            Avatar = "https://robohash.org/magnipariaturdolor.png?size=100x100&set=set1",
                            Department = "Business Development",
                            Email = "hupstone1b@bloglines.com",
                            FirstName = "Harriott",
                            LastName = "Upstone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
